name: gms_somatic
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.7
  - bcftools=1.11
  - pysam=0.16.0.1
  - pandas=1.2.1
  - fastp=0.20.1
  - bwa=0.7.17
  - samtools=1.11
  - bamtools=2.5.1
  - vardict-java=1.8.2
  - freebayes=1.3.2
  - parallel=20190522
  - bedtools=2.29
  - sed=4.7
  - snakemake-wrapper-utils=0.1.3
  - gatk4=4.1.9.0
  - picard=2.25.0
  - cnvkit=0.9.8
  - gridss=2.10.2
  - cutadapt=3.2
  - fastqc=0.11.9
  - multiqc=1.9
  - htslib=1.11
  - vt=2015.11.10
  - bcbio-variation-recall=0.2.6
  - ensembl-vep=103.1
